site_name: Dương Hứa Toàn (Tony) - Full-stack Developer
site_description: Professional resume and portfolio website
site_author: Dương Hứa Toàn (Tony)
site_url: https://huatoanduong.github.io

# Repository
repo_name: huatoanduong/huatoanduong.github.io
repo_url: https://github.com/huatoanduong/huatoanduong.github.io
edit_uri: edit/main/docs/

docs_dir: docs
site_dir: dist
dev_addr: localhost:5000

# Theme configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - header.autohide
    - navigation.footer

# Navigation
nav:
  - Home: index.md

# Markdown extensions
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.arithmatex
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Plugins
plugins:
  - search
  - minify:
      minify_html: true